target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'core', :path => '../core'
  pod 'FirebaseAuth', '10.3.0'
  pod 'FirebaseAnalytics', '10.3.0'
  pod 'FirebaseCrashlytics', '10.3.0'
end
